export const fakeData = [
  {
    idSV: 1,
    name: "Triết học Mác-Lênin",
    duration: 3,
    type: "Khối kiến thức chung",
    code: "PHI1006",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 1,
    name: "Kinh tế chính trị Mác-Lênin",
    duration: 2,
    type: "Khối kiến thức chung",
    code: "PEC1008",
    theoriticalHour: 20,
    practicalHour: 10,
    selfStudyHour: "",
    prerequisiteCode: "PHI1006",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 1,
    name: "Chủ nghĩa xã hội khoa học",
    duration: 2,
    type: "Khối kiến thức chung",
    code: "PHI1002",
    theoriticalHour: 30,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 1,
    name: "Lịch sử Đảng Cộng sản Việt Nam",
    duration: 2,
    type: "Khối kiến thức chung",
    code: "HIS1001",
    theoriticalHour: 20,
    practicalHour: 10,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 1,
    name: "Tư tưởng Hồ Chí Minh",
    duration: 2,
    type: "Khối kiến thức chung",
    code: "POL1001",
    theoriticalHour: 20,
    practicalHour: 10,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 1,
    name: "Tiếng Anh B1",
    duration: 5,
    type: "Khối kiến thức chung",
    code: "FLF1107",
    theoriticalHour: 20,
    practicalHour: 35,
    selfStudyHour: 20,
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 1,
    name: "Giáo dục thể chất",
    duration: 4,
    type: "Khối kiến thức chung",
    code: "",
    theoriticalHour: "",
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Giáo dục quốc phòng - an ninh",
    duration: 8,
    type: "Khối kiến thức chung",
    code: "",
    theoriticalHour: "",
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 1,
    name: "Đại số",
    duration: 4,
    type: "Khối kiến thức theo lĩnh vực",
    code: "MAT1093",
    theoriticalHour: 30,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 1,
    name: "Giải tích 1",
    duration: 4,
    type: "Khối kiến thức theo lĩnh vực",
    code: "MAT1041",
    theoriticalHour: 30,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 1,
    name: "Giải tích 2",
    duration: 4,
    type: "Khối kiến thức theo lĩnh vực",
    code: "MAT1402",
    theoriticalHour: 30,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "MAT1041",
    status: "ĐANG HỌC",
  },
  {
    idSV: 1,
    name: "Vật lý đại cương 1",
    duration: 2,
    type: "Khối kiến thức theo lĩnh vực",
    code: "EPN1095",
    theoriticalHour: 30,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 1,
    name: "Vật lý đại cương 2",
    duration: 2,
    type: "Khối kiến thức theo lĩnh vực",
    code: "EPN1096",
    theoriticalHour: 30,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "EPN1095",
    status: "ĐANG HỌC",
  },
  {
    idSV: 1,
    name: "Giới thiệu về Công nghệ thông tin",
    duration: 3,
    type: "Khối kiến thức theo lĩnh vực",
    code: "INT1007",
    theoriticalHour: 15,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐANG HỌC",
  },
  {
    idSV: 1,
    name: "Nhập môn lập trình",
    duration: 3,
    type: "Khối kiến thức theo lĩnh vực",
    code: "INT1008",
    theoriticalHour: 20,
    practicalHour: 25,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐANG HỌC",
  },
  {
    idSV: 1,
    name: "Xác suất thống kê",
    duration: 3,
    type: "Khối kiến thức theo khối ngành tự chọn",
    code: "MAT1101",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "MAT1041",
    status: "ĐANG HỌC",
  },
  {
    idSV: 1,
    name: "Tín hiệu và hệ thống",
    duration: 3,
    type: "Khối kiến thức theo khối ngành bắt buộc",
    code: "ELT2035",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "MAT1042",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 1,
    name: "Cấu trúc dữ liệu và giải thuật",
    duration: 4,
    type: "Khối kiến thức theo khối ngành bắt buộc",
    code: "ELT2029",
    theoriticalHour: 30,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "INT1008",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 1,
    name: "Toán trong công nghệ",
    duration: 3,
    type: "Khối kiến thức theo khối ngành tự chọn",
    code: "ELT2035",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "MAT1041",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Toán học rời rạc",
    duration: 4,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT1050",
    theoriticalHour: 45,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐANG HỌC",
  },
  {
    idSV: 1,
    name: "Lập trình nâng cao",
    duration: 4,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2215",
    theoriticalHour: 30,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "INT1008",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Kiến trúc máy tính",
    duration: 4,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2212",
    theoriticalHour: 45,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1007",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Nguyên lý hệ điều hành",
    duration: 4,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2214",
    theoriticalHour: 45,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1008",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Cơ sở dữ liệu",
    duration: 4,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2211",
    theoriticalHour: 30,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "INT1008",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Mạng máy tính",
    duration: 4,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2213",
    theoriticalHour: 30,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "INT1008",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Công nghệ phần mềm",
    duration: 3,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2008",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT1008",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Lập trình hướng đối tượng",
    duration: 3,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2204",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1008",
    status: "ĐANG HỌC",
  },
  {
    idSV: 1,
    name: "Hệ quản trị cơ sở dữ liệu",
    duration: 3,
    type: "Khối kiến thức ngành bắt buộc",
    code: "INT3202",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT2211",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Phân tích và thiết kế hướng đối tượng",
    duration: 3,
    type: "Khối kiến thức ngành bắt buộc",
    code: "INT3110",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2204",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Phát triển ứng dụng web",
    duration: 3,
    type: "Khối kiến thức ngành bắt buộc",
    code: "INT3306",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT2204, INT2211",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Trí tuệ nhân tạo",
    duration: 3,
    type: "Khối kiến thức ngành bắt buộc",
    code: "INT3401",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2210",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Các vấn đề hiện đại Công nghệ thông tin",
    duration: 3,
    type: "Khối kiến thức ngành bắt buộc",
    code: "INT3507",
    theoriticalHour: 21,
    practicalHour: 24,
    selfStudyHour: "",
    prerequisiteCode: "INT1007",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Thực tập chuyên ngành",
    duration: 3,
    type: "Khối kiến thức ngành bắt buộc",
    code: "INT3508",
    theoriticalHour: 15,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "INT1007",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Kiểm thử và đảm bảo chất lượng phần mềm",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3117",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2204",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Kiến trúc phần mềm",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3105",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2204",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Phương pháp hình thức",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3106",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1050",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Lập trình nhúng và thời gian thực",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3108",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT2212, INT2215",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Thu thập và phân tích yêu cầu",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3109",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2208",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Quản lý dự án phần mềm",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3111",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2208",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Thiết kế giao diện người dùng",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3115",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2204",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Phát triển ứng dụng di động",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3120",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1008",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Phát triển ứng dụng di động nâng cao",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3415",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1008",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Cơ sở dữ liệu phân tán",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3206",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2211",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Kho dữ liệu",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3207",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2211",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Khai phá dữ liệu",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3209",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2211",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Nhập môn an toàn thông tin",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3213",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Phân tích, đánh giá hiệu năng hệ thống",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3216",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2211",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Tích hợp hệ thống",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3211",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Phân tích thiết kế các HTTT",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT2020",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2211",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Thực hành hệ điều hành mạng",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3301",
    theoriticalHour: 15,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "INT1008",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Mạng không dây",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3303",
    theoriticalHour: 36,
    practicalHour: 9,
    selfStudyHour: "",
    prerequisiteCode: "INT2213",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Lập trình mạng",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3304",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT2213",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Truyền thông đa phương tiện",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3305",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2213",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "An toàn và an ninh mạng",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3307",
    theoriticalHour: 39,
    practicalHour: 6,
    selfStudyHour: "",
    prerequisiteCode: "INT2213",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Điện toán đám mây",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3319",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1008",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Quản trị mạng",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3310",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT2213",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Khoa học dịch vụ",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3501",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT1007",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Kiến trúc hướng dịch vụ",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3505",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2204",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Các hệ thống thương mại điện tử",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3506",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT1007",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Xử lý ảnh",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3404",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2210",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Lập trình thi đấu",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3512",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Tin sinh học",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3407",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2215",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Dự án công nghệ",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3132",
    theoriticalHour: 21,
    practicalHour: 24,
    selfStudyHour: "",
    prerequisiteCode: "INT2215",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Pháp luật và đạo đức nghề nghiệp trong CNTT",
    duration: 2,
    type: "Khối kiến thức bổ trợ bắt buộc",
    code: "INT3514",
    theoriticalHour: 30,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Phương pháp tính",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "INT3102",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "MAT1093, MAT1042",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Tối ưu hóa",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "INT3103",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "MAT1093, MAT1042",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Tiếng Anh bổ trợ",
    duration: 4,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "UET1001",
    theoriticalHour: 45,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Xử lý tín hiệu số",
    duration: 4,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "ELT3144",
    theoriticalHour: 45,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "MAT1093",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Linh kiện điện tử",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "ELT2032",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Kỹ thuật điện",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "ELT2030",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Điện tử tương tự",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "ELT2040",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Điện tử số",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "ELT2041",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Kinh tế vi mô",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "INE1050",
    theoriticalHour: 30,
    practicalHour: 10,
    selfStudyHour: 5,
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Nguyên lý quản trị kinh doanh",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "BSA2103",
    theoriticalHour: 27,
    practicalHour: 18,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Nguyên lý Marketing",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "BSA2002",
    theoriticalHour: 21,
    practicalHour: 23,
    selfStudyHour: 1,
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Khởi sự và tạo lập doanh nghiệp",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "BSA3020",
    theoriticalHour: 35,
    practicalHour: 10,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Lý luận về nhà nước và pháp luật",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "THL1054",
    theoriticalHour: 27,
    practicalHour: 12,
    selfStudyHour: 6,
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Lịch sử nhà nước và pháp luật",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "THL1058",
    theoriticalHour: 24,
    practicalHour: 15,
    selfStudyHour: 6,
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Luật hiến pháp",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "CAL1007",
    theoriticalHour: 36,
    practicalHour: "",
    selfStudyHour: 9,
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Luật hành chính",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "CAL1008",
    theoriticalHour: 30,
    practicalHour: 6,
    selfStudyHour: 9,
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Khóa luật tốt nghiệp",
    duration: 7,
    type: "Khóa luận tốt nghiệp",
    code: "INT4050",
    theoriticalHour: "",
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name: "Dự án",
    duration: 4,
    type: "Các học phần thay thế khóa luận tốt nghiệp",
    code: "INT3509",
    theoriticalHour: 21,
    practicalHour: "",
    selfStudyHour: 39,
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 1,
    name:
      "3 tín chỉ từ danh sách các học phần tự chọn theo các định hướng mà sinh viên CHƯA HỌC",
    duration: 3,
    type: "Các học phần thay thế khóa luận tốt nghiệp",
    code: "",
    theoriticalHour: "",
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Triết học Mác-Lênin",
    duration: 3,
    type: "Khối kiến thức chung",
    code: "PHI1006",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 2,
    name: "Kinh tế chính trị Mác-Lênin",
    duration: 2,
    type: "Khối kiến thức chung",
    code: "PEC1008",
    theoriticalHour: 20,
    practicalHour: 10,
    selfStudyHour: "",
    prerequisiteCode: "PHI1006",
    status: "ĐANG HỌC",
  },
  {
    idSV: 2,
    name: "Chủ nghĩa xã hội khoa học",
    duration: 2,
    type: "Khối kiến thức chung",
    code: "PHI1002",
    theoriticalHour: 30,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 2,
    name: "Lịch sử Đảng Cộng sản Việt Nam",
    duration: 2,
    type: "Khối kiến thức chung",
    code: "HIS1001",
    theoriticalHour: 20,
    practicalHour: 10,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐANG HỌC",
  },
  {
    idSV: 2,
    name: "Tư tưởng Hồ Chí Minh",
    duration: 2,
    type: "Khối kiến thức chung",
    code: "POL1001",
    theoriticalHour: 20,
    practicalHour: 10,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Tiếng Anh B1",
    duration: 5,
    type: "Khối kiến thức chung",
    code: "FLF1107",
    theoriticalHour: 20,
    practicalHour: 35,
    selfStudyHour: 20,
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 2,
    name: "Giáo dục thể chất",
    duration: 4,
    type: "Khối kiến thức chung",
    code: "",
    theoriticalHour: "",
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Giáo dục quốc phòng - an ninh",
    duration: 8,
    type: "Khối kiến thức chung",
    code: "",
    theoriticalHour: "",
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 2,
    name: "Đại số",
    duration: 4,
    type: "Khối kiến thức theo lĩnh vực",
    code: "MAT1093",
    theoriticalHour: 30,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 2,
    name: "Giải tích 1",
    duration: 4,
    type: "Khối kiến thức theo lĩnh vực",
    code: "MAT1041",
    theoriticalHour: 30,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐANG HỌC",
  },
  {
    idSV: 2,
    name: "Giải tích 2",
    duration: 4,
    type: "Khối kiến thức theo lĩnh vực",
    code: "MAT1402",
    theoriticalHour: 30,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "MAT1041",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Vật lý đại cương 1",
    duration: 2,
    type: "Khối kiến thức theo lĩnh vực",
    code: "EPN1095",
    theoriticalHour: 30,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐANG HỌC",
  },
  {
    idSV: 2,
    name: "Vật lý đại cương 2",
    duration: 2,
    type: "Khối kiến thức theo lĩnh vực",
    code: "EPN1096",
    theoriticalHour: 30,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "EPN1095",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Giới thiệu về Công nghệ thông tin",
    duration: 3,
    type: "Khối kiến thức theo lĩnh vực",
    code: "INT1007",
    theoriticalHour: 15,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐANG HỌC",
  },
  {
    idSV: 2,
    name: "Nhập môn lập trình",
    duration: 3,
    type: "Khối kiến thức theo lĩnh vực",
    code: "INT1008",
    theoriticalHour: 20,
    practicalHour: 25,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐANG HỌC",
  },
  {
    idSV: 2,
    name: "Xác suất thống kê",
    duration: 3,
    type: "Khối kiến thức theo khối ngành tự chọn",
    code: "MAT1101",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "MAT1041",
    status: "ĐANG HỌC",
  },
  {
    idSV: 2,
    name: "Tín hiệu và hệ thống",
    duration: 3,
    type: "Khối kiến thức theo khối ngành bắt buộc",
    code: "ELT2035",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "MAT1042",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Cấu trúc dữ liệu và giải thuật",
    duration: 4,
    type: "Khối kiến thức theo khối ngành bắt buộc",
    code: "ELT2029",
    theoriticalHour: 30,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "INT1008",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Toán trong công nghệ",
    duration: 3,
    type: "Khối kiến thức theo khối ngành tự chọn",
    code: "ELT2035",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "MAT1041",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Toán học rời rạc",
    duration: 4,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT1050",
    theoriticalHour: 45,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Lập trình nâng cao",
    duration: 4,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2215",
    theoriticalHour: 30,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "INT1008",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Kiến trúc máy tính",
    duration: 4,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2212",
    theoriticalHour: 45,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1007",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Nguyên lý hệ điều hành",
    duration: 4,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2214",
    theoriticalHour: 45,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1008",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Cơ sở dữ liệu",
    duration: 4,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2211",
    theoriticalHour: 30,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "INT1008",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Mạng máy tính",
    duration: 4,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2213",
    theoriticalHour: 30,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "INT1008",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Công nghệ phần mềm",
    duration: 3,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2008",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT1008",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Lập trình hướng đối tượng",
    duration: 3,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2204",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1008",
    status: "ĐANG HỌC",
  },
  {
    idSV: 2,
    name: "Hệ quản trị cơ sở dữ liệu",
    duration: 3,
    type: "Khối kiến thức ngành bắt buộc",
    code: "INT3202",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT2211",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Phân tích và thiết kế hướng đối tượng",
    duration: 3,
    type: "Khối kiến thức ngành bắt buộc",
    code: "INT3110",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2204",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Phát triển ứng dụng web",
    duration: 3,
    type: "Khối kiến thức ngành bắt buộc",
    code: "INT3306",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT2204, INT2211",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Trí tuệ nhân tạo",
    duration: 3,
    type: "Khối kiến thức ngành bắt buộc",
    code: "INT3401",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2210",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Các vấn đề hiện đại Công nghệ thông tin",
    duration: 3,
    type: "Khối kiến thức ngành bắt buộc",
    code: "INT3507",
    theoriticalHour: 21,
    practicalHour: 24,
    selfStudyHour: "",
    prerequisiteCode: "INT1007",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Thực tập chuyên ngành",
    duration: 3,
    type: "Khối kiến thức ngành bắt buộc",
    code: "INT3508",
    theoriticalHour: 15,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "INT1007",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Kiểm thử và đảm bảo chất lượng phần mềm",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3117",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2204",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Kiến trúc phần mềm",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3105",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2204",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Phương pháp hình thức",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3106",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1050",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Lập trình nhúng và thời gian thực",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3108",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT2212, INT2215",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Thu thập và phân tích yêu cầu",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3109",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2208",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Quản lý dự án phần mềm",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3111",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2208",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Thiết kế giao diện người dùng",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3115",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2204",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Phát triển ứng dụng di động",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3120",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1008",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Phát triển ứng dụng di động nâng cao",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3415",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1008",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Cơ sở dữ liệu phân tán",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3206",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2211",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Kho dữ liệu",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3207",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2211",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Khai phá dữ liệu",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3209",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2211",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Nhập môn an toàn thông tin",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3213",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Phân tích, đánh giá hiệu năng hệ thống",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3216",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2211",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Tích hợp hệ thống",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3211",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Phân tích thiết kế các HTTT",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT2020",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2211",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Thực hành hệ điều hành mạng",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3301",
    theoriticalHour: 15,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "INT1008",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Mạng không dây",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3303",
    theoriticalHour: 36,
    practicalHour: 9,
    selfStudyHour: "",
    prerequisiteCode: "INT2213",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Lập trình mạng",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3304",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT2213",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Truyền thông đa phương tiện",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3305",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2213",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "An toàn và an ninh mạng",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3307",
    theoriticalHour: 39,
    practicalHour: 6,
    selfStudyHour: "",
    prerequisiteCode: "INT2213",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Điện toán đám mây",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3319",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1008",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Quản trị mạng",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3310",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT2213",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Khoa học dịch vụ",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3501",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT1007",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Kiến trúc hướng dịch vụ",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3505",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2204",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Các hệ thống thương mại điện tử",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3506",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT1007",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Xử lý ảnh",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3404",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2210",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Lập trình thi đấu",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3512",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Tin sinh học",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3407",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2215",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Dự án công nghệ",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3132",
    theoriticalHour: 21,
    practicalHour: 24,
    selfStudyHour: "",
    prerequisiteCode: "INT2215",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Pháp luật và đạo đức nghề nghiệp trong CNTT",
    duration: 2,
    type: "Khối kiến thức bổ trợ bắt buộc",
    code: "INT3514",
    theoriticalHour: 30,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Phương pháp tính",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "INT3102",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "MAT1093, MAT1042",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Tối ưu hóa",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "INT3103",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "MAT1093, MAT1042",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Tiếng Anh bổ trợ",
    duration: 4,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "UET1001",
    theoriticalHour: 45,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Xử lý tín hiệu số",
    duration: 4,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "ELT3144",
    theoriticalHour: 45,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "MAT1093",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Linh kiện điện tử",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "ELT2032",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Kỹ thuật điện",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "ELT2030",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Điện tử tương tự",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "ELT2040",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Điện tử số",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "ELT2041",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Kinh tế vi mô",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "INE1050",
    theoriticalHour: 30,
    practicalHour: 10,
    selfStudyHour: 5,
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Nguyên lý quản trị kinh doanh",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "BSA2103",
    theoriticalHour: 27,
    practicalHour: 18,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Nguyên lý Marketing",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "BSA2002",
    theoriticalHour: 21,
    practicalHour: 23,
    selfStudyHour: 1,
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Khởi sự và tạo lập doanh nghiệp",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "BSA3020",
    theoriticalHour: 35,
    practicalHour: 10,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Lý luận về nhà nước và pháp luật",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "THL1054",
    theoriticalHour: 27,
    practicalHour: 12,
    selfStudyHour: 6,
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Lịch sử nhà nước và pháp luật",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "THL1058",
    theoriticalHour: 24,
    practicalHour: 15,
    selfStudyHour: 6,
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Luật hiến pháp",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "CAL1007",
    theoriticalHour: 36,
    practicalHour: "",
    selfStudyHour: 9,
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Luật hành chính",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "CAL1008",
    theoriticalHour: 30,
    practicalHour: 6,
    selfStudyHour: 9,
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Khóa luật tốt nghiệp",
    duration: 7,
    type: "Khóa luận tốt nghiệp",
    code: "INT4050",
    theoriticalHour: "",
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name: "Dự án",
    duration: 4,
    type: "Các học phần thay thế khóa luận tốt nghiệp",
    code: "INT3509",
    theoriticalHour: 21,
    practicalHour: "",
    selfStudyHour: 39,
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 2,
    name:
      "3 tín chỉ từ danh sách các học phần tự chọn theo các định hướng mà sinh viên CHƯA HỌC",
    duration: 3,
    type: "Các học phần thay thế khóa luận tốt nghiệp",
    code: "",
    theoriticalHour: "",
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 3,
    name: "Những nguyên lý cơ bản của chủ nghĩa Mác - Lênin 1",
    duration: 2,
    type: "Khối kiến thức chung",
    code: "PHI1004",
    theoriticalHour: 24,
    practicalHour: 6,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Những nguyên lý cơ bản của chủ nghĩa Mác - Lênin 2",
    duration: 3,
    type: "Khối kiến thức chung",
    code: "PHI1005",
    theoriticalHour: 36,
    practicalHour: 9,
    selfStudyHour: "",
    prerequisiteCode: "PHI1004",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Tư tưởng Hồ Chí Minh",
    duration: 2,
    type: "Khối kiến thức chung",
    code: "POL1001",
    theoriticalHour: 20,
    practicalHour: 10,
    selfStudyHour: "",
    prerequisiteCode: "PHI1005",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Đường lối cách mạng của Đảng Cộng sản Việt Nam",
    duration: 3,
    type: "Khối kiến thức chung",
    code: "HIS1002",
    theoriticalHour: 42,
    practicalHour: 3,
    selfStudyHour: "",
    prerequisiteCode: "POL1001",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Tin học cơ sở 1",
    duration: 2,
    type: "Khối kiến thức chung",
    code: "INT1003",
    theoriticalHour: 10,
    practicalHour: 20,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Tin học cơ sở 4",
    duration: 3,
    type: "Khối kiến thức chung",
    code: "INT1006",
    theoriticalHour: 20,
    practicalHour: 23,
    selfStudyHour: 2,
    prerequisiteCode: "INT1003",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Tiếng Anh cơ sở 1",
    duration: 4,
    type: "Khối kiến thức chung",
    code: "FLF2101",
    theoriticalHour: 16,
    practicalHour: 40,
    selfStudyHour: 4,
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Tiếng Anh cơ sở 2",
    duration: 5,
    type: "Khối kiến thức chung",
    code: "FLF2102",
    theoriticalHour: 20,
    practicalHour: 50,
    selfStudyHour: 5,
    prerequisiteCode: "FLF2101",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Tiếng Anh cơ sở 3",
    duration: 5,
    type: "Khối kiến thức chung",
    code: "FLF2103",
    theoriticalHour: 20,
    practicalHour: 50,
    selfStudyHour: 5,
    prerequisiteCode: "FLF2102",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Giáo dục thể chất",
    duration: 4,
    type: "Khối kiến thức chung",
    code: "",
    theoriticalHour: "",
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Giáo dục quốc phòng - an ninh",
    duration: 8,
    type: "Khối kiến thức chung",
    code: "",
    theoriticalHour: "",
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Kỹ năng bổ trợ",
    duration: 3,
    type: "Khối kiến thức chung",
    code: "",
    theoriticalHour: "",
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Đại số",
    duration: 4,
    type: "Khối kiến thức theo lĩnh vực",
    code: "MAT1093",
    theoriticalHour: 30,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Giải tích 1",
    duration: 4,
    type: "Khối kiến thức theo lĩnh vực",
    code: "MAT1041",
    theoriticalHour: 30,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Đại số",
    duration: 4,
    type: "Khối kiến thức theo lĩnh vực",
    code: "MAT1042",
    theoriticalHour: 30,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "MAT1041",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Cơ - Nhiệt",
    duration: 3,
    type: "Khối kiến thức theo lĩnh vực",
    code: "PHY1100",
    theoriticalHour: 32,
    practicalHour: 10,
    selfStudyHour: 3,
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Điện và Quang",
    duration: 3,
    type: "Khối kiến thức theo lĩnh vực",
    code: "PHY1103",
    theoriticalHour: 32,
    practicalHour: 10,
    selfStudyHour: 3,
    prerequisiteCode: "PHI1100",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Tín hiệu và hệ thống",
    duration: 3,
    type: "Khối kiến thức theo khối ngành bắt buộc",
    code: "ELT2035",
    theoriticalHour: 42,
    practicalHour: 3,
    selfStudyHour: "",
    prerequisiteCode: "MAT1042",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Cấu trúc dữ liệu và giải thuật",
    duration: 3,
    type: "Khối kiến thức theo khối ngành bắt buộc",
    code: "INT2203",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1006",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Xác suất thống kê",
    duration: 3,
    type: "Khối kiến thức theo khối ngành tự chọn",
    code: "MAT1101",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "MAT1041",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Toán trong công nghệ",
    duration: 3,
    type: "Khối kiến thức theo khối ngành tự chọn",
    code: "ELT2029",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "MAT1041",
    status: "CHƯA HỌC",
  },
  {
    idSV: 3,
    name: "Lập trình hướng đối tượng",
    duration: 3,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2204",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1006",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Kiến trúc máy tính",
    duration: 3,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2205",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT1003",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Toán học rời rạc",
    duration: 4,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT1050",
    theoriticalHour: 45,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Nguyên lý hệ điều hành",
    duration: 3,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2206",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT1006",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Mạng máy tính",
    duration: 3,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2209",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1006",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Công nghệ phần mềm",
    duration: 3,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2208",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT1006",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Cơ sở dữ liệu",
    duration: 3,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2207",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1006",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Lập trình nâng cao",
    duration: 3,
    type: "Khối kiến thức ngành bắt buộc",
    code: "INT2204",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1006",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Trí tuệ nhân tạo",
    duration: 3,
    type: "Khối kiến thức ngành bắt buộc",
    code: "INT3401",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2203",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Đồ họa máy tính",
    duration: 3,
    type: "Khối kiến thức ngành bắt buộc",
    code: "INT3403",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT2203",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Lý thuyết thông tin",
    duration: 3,
    type: "Khối kiến thức ngành bắt buộc",
    code: "INT2044",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "MAT1101",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Chuyên đề Công nghệ",
    duration: 3,
    type: "Khối kiến thức ngành bắt buộc",
    code: "INT3414",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1003",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Thực tập chuyên ngành",
    duration: 3,
    type: "Khối kiến thức ngành bắt buộc",
    code: "INT3508",
    theoriticalHour: 15,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "INT1003",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Chương trình dịch",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3402",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2203",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Xử lý ảnh",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3404",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2203",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Học máy",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3405",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "MAT1101",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Xử lý ngôn ngữ tự nhiên",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3406",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2203",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Tin sinh học",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3407",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2202",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Rô-bốt",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3409",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT2203",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Xử lý tiếng nói",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3411",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2203",
    status: "CHƯA HỌC",
  },
  {
    idSV: 3,
    name: "Thị giác máy",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3412",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2203",
    status: "CHƯA HỌC",
  },
  {
    idSV: 3,
    name: "Các vấn đề hiện đại trong KHMT",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3011",
    theoriticalHour: 21,
    practicalHour: "",
    selfStudyHour: 24,
    prerequisiteCode: "INT1003",
    status: "CHƯA HỌC",
  },
  {
    idSV: 3,
    name: "Kiểm thử và đảm bảo chất lượng phần mềm",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3417",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2204",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Kiến trúc phần mềm",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3105",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2204",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Lập trình nhúng và thời gian thực",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3108",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT2205, INT2202",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Ứng dụng di động cho điện toán đám mây",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3122",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2204",
    status: "CHƯA HỌC",
  },
  {
    idSV: 3,
    name: "Phân tích và thiết kế hướng đối tượng",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3110",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2204",
    status: "CHƯA HỌC",
  },
  {
    idSV: 3,
    name: "Quản lý dự án phần mềm",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3111",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2208",
    status: "CHƯA HỌC",
  },
  {
    idSV: 3,
    name: "Cơ sở dữ liệu đa phương tiện",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3222",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2207",
    status: "CHƯA HỌC",
  },
  {
    idSV: 3,
    name: "Khai phá dữ liệu",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3209",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2207",
    status: "CHƯA HỌC",
  },
  {
    idSV: 3,
    name: "Lập trình mạng",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3304",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT2209",
    status: "CHƯA HỌC",
  },
  {
    idSV: 3,
    name: "Truyền thông đa phương tiện",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3305",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2209",
    status: "CHƯA HỌC",
  },
  {
    idSV: 3,
    name: "Phát triển ứng dụng Web",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3306",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT2204 , INT2207",
    status: "CHƯA HỌC",
  },
  {
    idSV: 3,
    name: "An toàn và an ninh mạng",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3307",
    theoriticalHour: 39,
    practicalHour: 6,
    selfStudyHour: "",
    prerequisiteCode: "INT2209",
    status: "CHƯA HỌC",
  },
  {
    idSV: 3,
    name: "Kiến trúc hướng dịch vụ",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3505",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2204",
    status: "CHƯA HỌC",
  },
  {
    idSV: 3,
    name: "Các chuyên đề trong KHMT",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3121",
    theoriticalHour: 21,
    practicalHour: "",
    selfStudyHour: 24,
    prerequisiteCode: "INT2203, INT1101",
    status: "CHƯA HỌC",
  },
  {
    idSV: 3,
    name: "Phương pháp tính",
    duration: 2,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "INT1099",
    theoriticalHour: 30,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "MAT1093 , MAT1042",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Tối ưu hóa",
    duration: 2,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "MAT1100",
    theoriticalHour: 30,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "MAT1093 , MAT1042",
    status: "CHƯA HỌC",
  },
  {
    idSV: 3,
    name: "Chuyên nghiệp trong công nghệ",
    duration: 2,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "ELT2028",
    theoriticalHour: 30,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 3,
    name: "Mô hình hóa và mô phỏng",
    duration: 2,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "ELT2031",
    theoriticalHour: 20,
    practicalHour: 10,
    selfStudyHour: "",
    prerequisiteCode: "INT1006",
    status: "CHƯA HỌC",
  },
  {
    idSV: 3,
    name: "Xử lý tín hiệu số",
    duration: 4,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "ELT3144",
    theoriticalHour: 45,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "MAT1093",
    status: "CHƯA HỌC",
  },
  {
    idSV: 3,
    name: "Nguyên lý Marketing",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "BSA2022",
    theoriticalHour: 21,
    practicalHour: 23,
    selfStudyHour: 1,
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 3,
    name: "Kinh tế vi mô 1",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "INE1150",
    theoriticalHour: 30,
    practicalHour: 10,
    selfStudyHour: 5,
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 3,
    name: "Kinh tế vĩ mô 1",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "INE1151",
    theoriticalHour: 30,
    practicalHour: 10,
    selfStudyHour: 5,
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 3,
    name: "Khóa luận tốt nghiệp",
    duration: 7,
    type: "Khóa luận tốt nghiệp",
    code: "INT4050",
    theoriticalHour: "",
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐANG HỌC",
  },
  {
    idSV: 3,
    name: "Dự án",
    duration: 4,
    type: "Khóa luận tốt nghiệp",
    code: "INT3509",
    theoriticalHour: "",
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 3,
    name:
      "3 tín chỉ từ danh sách các học phần thuộc khối kiến thức ngành tự chọn mà sinh viên chưa học",
    duration: 3,
    type: "Khóa luận tốt nghiệp",
    code: "",
    theoriticalHour: "",
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Những nguyên lý cơ bản của chủ nghĩa Mác - Lênin 1",
    duration: 2,
    type: "Khối kiến thức chung",
    code: "PHI1004",
    theoriticalHour: 24,
    practicalHour: 6,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Những nguyên lý cơ bản của chủ nghĩa Mác - Lênin 2",
    duration: 3,
    type: "Khối kiến thức chung",
    code: "PHI1005",
    theoriticalHour: 36,
    practicalHour: 9,
    selfStudyHour: "",
    prerequisiteCode: "PHI1004",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Tư tưởng Hồ Chí Minh",
    duration: 2,
    type: "Khối kiến thức chung",
    code: "POL1001",
    theoriticalHour: 20,
    practicalHour: 10,
    selfStudyHour: "",
    prerequisiteCode: "PHI1005",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Đường lối cách mạng của Đảng Cộng sản Việt Nam",
    duration: 3,
    type: "Khối kiến thức chung",
    code: "HIS1002",
    theoriticalHour: 42,
    practicalHour: 3,
    selfStudyHour: "",
    prerequisiteCode: "POL1001",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Tin học cơ sở 1",
    duration: 2,
    type: "Khối kiến thức chung",
    code: "INT1003",
    theoriticalHour: 10,
    practicalHour: 20,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Tin học cơ sở 4",
    duration: 3,
    type: "Khối kiến thức chung",
    code: "INT1006",
    theoriticalHour: 20,
    practicalHour: 23,
    selfStudyHour: 2,
    prerequisiteCode: "INT1003",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Tiếng Anh cơ sở 1",
    duration: 4,
    type: "Khối kiến thức chung",
    code: "FLF2101",
    theoriticalHour: 16,
    practicalHour: 40,
    selfStudyHour: 4,
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Tiếng Anh cơ sở 2",
    duration: 5,
    type: "Khối kiến thức chung",
    code: "FLF2102",
    theoriticalHour: 20,
    practicalHour: 50,
    selfStudyHour: 5,
    prerequisiteCode: "FLF2101",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Tiếng Anh cơ sở 3",
    duration: 5,
    type: "Khối kiến thức chung",
    code: "FLF2103",
    theoriticalHour: 20,
    practicalHour: 50,
    selfStudyHour: 5,
    prerequisiteCode: "FLF2102",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Giáo dục thể chất",
    duration: 4,
    type: "Khối kiến thức chung",
    code: "",
    theoriticalHour: "",
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Giáo dục quốc phòng - an ninh",
    duration: 8,
    type: "Khối kiến thức chung",
    code: "",
    theoriticalHour: "",
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Kỹ năng bổ trợ",
    duration: 3,
    type: "Khối kiến thức chung",
    code: "",
    theoriticalHour: "",
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Đại số",
    duration: 4,
    type: "Khối kiến thức theo lĩnh vực",
    code: "MAT1093",
    theoriticalHour: 30,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Giải tích 1",
    duration: 4,
    type: "Khối kiến thức theo lĩnh vực",
    code: "MAT1041",
    theoriticalHour: 30,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Đại số",
    duration: 4,
    type: "Khối kiến thức theo lĩnh vực",
    code: "MAT1042",
    theoriticalHour: 30,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "MAT1041",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Cơ - Nhiệt",
    duration: 3,
    type: "Khối kiến thức theo lĩnh vực",
    code: "PHY1100",
    theoriticalHour: 32,
    practicalHour: 10,
    selfStudyHour: 3,
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Điện và Quang",
    duration: 3,
    type: "Khối kiến thức theo lĩnh vực",
    code: "PHY1103",
    theoriticalHour: 32,
    practicalHour: 10,
    selfStudyHour: 3,
    prerequisiteCode: "PHI1100",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Tín hiệu và hệ thống",
    duration: 3,
    type: "Khối kiến thức theo khối ngành bắt buộc",
    code: "ELT2035",
    theoriticalHour: 42,
    practicalHour: 3,
    selfStudyHour: "",
    prerequisiteCode: "MAT1042",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Cấu trúc dữ liệu và giải thuật",
    duration: 3,
    type: "Khối kiến thức theo khối ngành bắt buộc",
    code: "INT2203",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1006",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Xác suất thống kê",
    duration: 3,
    type: "Khối kiến thức theo khối ngành tự chọn",
    code: "MAT1101",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "MAT1041",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Toán trong công nghệ",
    duration: 3,
    type: "Khối kiến thức theo khối ngành tự chọn",
    code: "ELT2029",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "MAT1041",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Lập trình hướng đối tượng",
    duration: 3,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2204",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1006",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Kiến trúc máy tính",
    duration: 3,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2205",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT1003",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Toán học rời rạc",
    duration: 4,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT1050",
    theoriticalHour: 45,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Nguyên lý hệ điều hành",
    duration: 3,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2206",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT1006",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Mạng máy tính",
    duration: 3,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2209",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1006",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Công nghệ phần mềm",
    duration: 3,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2208",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT1006",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Cơ sở dữ liệu",
    duration: 3,
    type: "Khối kiến thức theo nhóm ngành bắt buộc",
    code: "INT2207",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1006",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Lập trình nâng cao",
    duration: 3,
    type: "Khối kiến thức ngành bắt buộc",
    code: "INT2204",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1006",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Trí tuệ nhân tạo",
    duration: 3,
    type: "Khối kiến thức ngành bắt buộc",
    code: "INT3401",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2203",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Đồ họa máy tính",
    duration: 3,
    type: "Khối kiến thức ngành bắt buộc",
    code: "INT3403",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT2203",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Lý thuyết thông tin",
    duration: 3,
    type: "Khối kiến thức ngành bắt buộc",
    code: "INT2044",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "MAT1101",
    status: "ĐANG HỌC",
  },
  {
    idSV: 4,
    name: "Chuyên đề Công nghệ",
    duration: 3,
    type: "Khối kiến thức ngành bắt buộc",
    code: "INT3414",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT1003",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Thực tập chuyên ngành",
    duration: 3,
    type: "Khối kiến thức ngành bắt buộc",
    code: "INT3508",
    theoriticalHour: 15,
    practicalHour: 30,
    selfStudyHour: "",
    prerequisiteCode: "INT1003",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Chương trình dịch",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3402",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2203",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Xử lý ảnh",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3404",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2203",
    status: "ĐANG HỌC",
  },
  {
    idSV: 4,
    name: "Học máy",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3405",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "MAT1101",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Xử lý ngôn ngữ tự nhiên",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3406",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2203",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Tin sinh học",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3407",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2202",
    status: "ĐANG HỌC",
  },
  {
    idSV: 4,
    name: "Rô-bốt",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3409",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT2203",
    status: "ĐANG HỌC",
  },
  {
    idSV: 4,
    name: "Xử lý tiếng nói",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3411",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2203",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Thị giác máy",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3412",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2203",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Các vấn đề hiện đại trong KHMT",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3011",
    theoriticalHour: 21,
    practicalHour: "",
    selfStudyHour: 24,
    prerequisiteCode: "INT1003",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Kiểm thử và đảm bảo chất lượng phần mềm",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3417",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2204",
    status: "ĐANG HỌC",
  },
  {
    idSV: 4,
    name: "Kiến trúc phần mềm",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3105",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2204",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Lập trình nhúng và thời gian thực",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3108",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT2205, INT2202",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Ứng dụng di động cho điện toán đám mây",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3122",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2204",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Phân tích và thiết kế hướng đối tượng",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3110",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2204",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Quản lý dự án phần mềm",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3111",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2208",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Cơ sở dữ liệu đa phương tiện",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3222",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2207",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Khai phá dữ liệu",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3209",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2207",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Lập trình mạng",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3304",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT2209",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Truyền thông đa phương tiện",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3305",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2209",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Phát triển ứng dụng Web",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3306",
    theoriticalHour: 30,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "INT2204 , INT2207",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "An toàn và an ninh mạng",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3307",
    theoriticalHour: 39,
    practicalHour: 6,
    selfStudyHour: "",
    prerequisiteCode: "INT2209",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Kiến trúc hướng dịch vụ",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3505",
    theoriticalHour: 45,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "INT2204",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Các chuyên đề trong KHMT",
    duration: 3,
    type: "Khối kiến thức ngành tự chọn",
    code: "INT3121",
    theoriticalHour: 21,
    practicalHour: "",
    selfStudyHour: 24,
    prerequisiteCode: "INT2203, INT1101",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Phương pháp tính",
    duration: 2,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "INT1099",
    theoriticalHour: 30,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "MAT1093 , MAT1042",
    status: "ĐÃ HỌC",
  },
  {
    idSV: 4,
    name: "Tối ưu hóa",
    duration: 2,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "MAT1100",
    theoriticalHour: 30,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "MAT1093 , MAT1042",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Chuyên nghiệp trong công nghệ",
    duration: 2,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "ELT2028",
    theoriticalHour: 30,
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Mô hình hóa và mô phỏng",
    duration: 2,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "ELT2031",
    theoriticalHour: 20,
    practicalHour: 10,
    selfStudyHour: "",
    prerequisiteCode: "INT1006",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Xử lý tín hiệu số",
    duration: 4,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "ELT3144",
    theoriticalHour: 45,
    practicalHour: 15,
    selfStudyHour: "",
    prerequisiteCode: "MAT1093",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Nguyên lý Marketing",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "BSA2022",
    theoriticalHour: 21,
    practicalHour: 23,
    selfStudyHour: 1,
    prerequisiteCode: "",
    status: "ĐANG HỌC",
  },
  {
    idSV: 4,
    name: "Kinh tế vi mô 1",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "INE1150",
    theoriticalHour: 30,
    practicalHour: 10,
    selfStudyHour: 5,
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Kinh tế vĩ mô 1",
    duration: 3,
    type: "Khối kiến thức bổ trợ tự chọn",
    code: "INE1151",
    theoriticalHour: 30,
    practicalHour: 10,
    selfStudyHour: 5,
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Khóa luận tốt nghiệp",
    duration: 7,
    type: "Khóa luận tốt nghiệp",
    code: "INT4050",
    theoriticalHour: "",
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name: "Dự án",
    duration: 4,
    type: "Khóa luận tốt nghiệp",
    code: "INT3509",
    theoriticalHour: "",
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
  {
    idSV: 4,
    name:
      "3 tín chỉ từ danh sách các học phần thuộc khối kiến thức ngành tự chọn mà sinh viên chưa học",
    duration: 3,
    type: "Khóa luận tốt nghiệp",
    code: "",
    theoriticalHour: "",
    practicalHour: "",
    selfStudyHour: "",
    prerequisiteCode: "",
    status: "CHƯA HỌC",
  },
];
